add({ source = 'akinsho/git-conflict.nvim' })

later(function()
  require('git-conflict').setup()
  vim.keymap.set("n", "<Leader>gC", "", { desc = "Git Conflicts" })
  vim.keymap.set("n", "<Leader>gCo", ":GitConflictChooseOurs<CR>", { desc = "Choose Ours" })
  vim.keymap.set("n", "<Leader>gCt", ":GitConflictChooseTheirs<CR>", { desc = "Choose Theirs" })
  vim.keymap.set("n", "<Leader>gCb", ":GitConflictChooseBoth<CR>", { desc = "Choose Both" })
  vim.keymap.set("n", "<Leader>gCn", ":GitConflictChooseNone<CR>", { desc = "Choose None" })
  vim.keymap.set("n", "<Leader>gCN", ":GitConflictNextConflict<CR>", { desc = "Next Conflict" })
  vim.keymap.set("n", "<Leader>gCp", ":GitConflictPrevConflict<CR>", { desc = "Previous Conflict" })
  vim.keymap.set("n", "<Leader>gCl", ":GitConflictPrevConflict<CR>", { desc = "List Conflict" })
end)
